Kitty:
	./GifConverter /Users/thomas/Work/Project-Cube/Assets/Graphics/Kitty/Adult/ /Users/thomas/Work/Project-Cube/Assets/Characters/Kitty/Animations/Adult/
	./GifConverter /Users/thomas/Work/Project-Cube/Assets/Graphics/Kitty/Child/ /Users/thomas/Work/Project-Cube/Assets/Characters/Kitty/Animations/Child/
	./GifConverter /Users/thomas/Work/Project-Cube/Assets/Graphics/Kitty/NewBorn/ /Users/thomas/Work/Project-Cube/Assets/Characters/Kitty/Animations/NewBorn/